import json
from pathlib import Path

PATH = Path('assets/data/words.json')

grades = {
'1': [('rainbow','قوس قزح'),('playground','ساحة اللعب'),('lunchbox','صندوق الغداء'),('pencilcase','مقلمة'),('notebook','دفتر'),('crayon','قلم تلوين'),('eraser','ممحاة'),('ruler','مسطرة'),('picture','صورة'),('story','قصة'),('garden','حديقة'),('flower','زهرة'),('tree','شجرة'),('leaf','ورقة شجر'),('rabbit','أرنب'),('turtle','سلحفاة'),('monkey','قرد'),('lion','أسد'),('zebra','حمار وحشي'),('giraffe','زرافة'),('breakfast','فطور'),('cheese','جبن'),('juice','عصير'),('soup','حساء'),('cookie','بسكويت'),('bedroom','غرفة نوم'),('kitchen','مطبخ'),('bathroom','حمام'),('family','عائلة'),('sister','أخت'),('brother','أخ'),('grandmother','جدة'),('grandfather','جد'),('morning','صباح'),('evening','مساء'),('today','اليوم'),('tomorrow','غدًا'),('clean','نظيف'),('dirty','متسخ'),('strong','قوي'),('kind','لطيف'),('funny','مضحك'),('quiet','هادئ'),('loud','صاخب'),('smile','ابتسامة'),('laugh','يضحك'),('clap','يصفق'),('draw','يرسم'),('paint','يلوّن'),('count','يعد'),('spell','يتهجى'),('open','يفتح'),('close','يغلق'),('carry','يحمل'),('share','يشارك'),('help','يساعد'),('listen','يستمع'),('speak','يتحدث'),('learn','يتعلم'),('remember','يتذكر')],
'2': [('weather','الطقس'),('cloud','سحابة'),('storm','عاصفة'),('wind','رياح'),('season','فصل'),('spring','الربيع'),('summer','الصيف'),('autumn','الخريف'),('winter','الشتاء'),('market','سوق'),('bakery','مخبز'),('hospital','مستشفى'),('library','مكتبة'),('museum','متحف'),('station','محطة'),('street','شارع'),('village','قرية'),('city','مدينة'),('country','بلد'),('farmer','مزارع'),('doctor','طبيب'),('nurse','ممرض'),('driver','سائق'),('artist','فنان'),('student','طالب'),('homework','واجب منزلي'),('question','سؤال'),('answer','إجابة'),('lesson','درس'),('break','استراحة'),('healthy','صحي'),('hungry','جائع'),('thirsty','عطشان'),('tired','متعب'),('excited','متحمس'),('afraid','خائف'),('careful','حذر'),('quick','سريع'),('slow','بطيء'),('early','مبكر'),('late','متأخر'),('visit','يزور'),('travel','يسافر'),('build','يبني'),('wash','يغسل'),('cook','يطبخ'),('plant','يزرع'),('grow','ينمو'),('collect','يجمع'),('choose','يختار'),('finish','ينهي'),('begin','يبدأ'),('follow','يتبع'),('cross','يعبر'),('wait','ينتظر'),('invite','يدعو'),('enjoy','يستمتع'),('practice','يتدرب'),('repeat','يكرر'),('compare','يقارن')],
'3': [('adventure','مغامرة'),('journey','رحلة'),('island','جزيرة'),('forest','غابة'),('river','نهر'),('mountain','جبل'),('desert','صحراء'),('ocean','محيط'),('bridge','جسر'),('castle','قلعة'),('history','تاريخ'),('future','مستقبل'),('calendar','تقويم'),('minute','دقيقة'),('hour','ساعة'),('weekend','عطلة نهاية الأسبوع'),('hobby','هواية'),('football','كرة القدم'),('swimming','سباحة'),('cycling','ركوب الدراجات'),('music','موسيقى'),('science','علوم'),('nature','طبيعة'),('planet','كوكب'),('energy','طاقة'),('light','ضوء'),('shadow','ظل'),('shape','شكل'),('measure','يقيس'),('problem','مشكلة'),('solution','حل'),('important','مهم'),('different','مختلف'),('similar','مشابه'),('possible','ممكن'),('special','مميز'),('friendly','ودود'),('brave','شجاع'),('honest','صادق'),('useful','مفيد'),('discover','يكتشف'),('explore','يستكشف'),('protect','يحمي'),('create','ينشئ'),('imagine','يتخيل'),('explain','يشرح'),('describe','يصف'),('decide','يقرر'),('prepare','يجهز'),('improve','يحسن'),('return','يعود'),('arrive','يصل'),('borrow','يستعير'),('lend','يعير'),('promise','يعد'),('celebrate','يحتفل'),('recycle','يعيد التدوير'),('save','يوفر'),('waste','يهدر'),('respect','يحترم')],
'4': [('environment','البيئة'),('pollution','التلوث'),('recycling','إعادة التدوير'),('wildlife','الحياة البرية'),('habitat','موطن طبيعي'),('climate','المناخ'),('temperature','درجة الحرارة'),('population','السكان'),('community','المجتمع'),('culture','الثقافة'),('tradition','تقليد'),('festival','مهرجان'),('language','لغة'),('conversation','محادثة'),('message','رسالة'),('information','معلومات'),('computer','حاسوب'),('internet','الإنترنت'),('website','موقع إلكتروني'),('camera','كاميرا'),('machine','آلة'),('engine','محرك'),('material','مادة'),('experiment','تجربة'),('result','نتيجة'),('research','بحث'),('project','مشروع'),('teamwork','عمل جماعي'),('leader','قائد'),('member','عضو'),('responsible','مسؤول'),('creative','مبدع'),('successful','ناجح'),('dangerous','خطير'),('natural','طبيعي'),('modern','حديث'),('ancient','قديم'),('local','محلي'),('international','دولي'),('popular','شائع'),('organize','ينظم'),('design','يصمم'),('invent','يخترع'),('communicate','يتواصل'),('develop','يطور'),('reduce','يقلل'),('reuse','يعيد الاستخدام'),('repair','يصلح'),('observe','يلاحظ'),('record','يسجل'),('predict','يتوقع'),('connect','يربط'),('separate','يفصل'),('include','يتضمن'),('support','يدعم'),('provide','يوفر'),('increase','يزيد'),('decrease','ينقص'),('change','يغير'),('continue','يستمر')],
'5': [('technology','التكنولوجيا'),('device','جهاز'),('digital','رقمي'),('robot','روبوت'),('program','برنامج'),('screen','شاشة'),('battery','بطارية'),('signal','إشارة'),('network','شبكة'),('data','بيانات'),('health','الصحة'),('exercise','تمرين'),('nutrition','تغذية'),('medicine','دواء'),('disease','مرض'),('safety','السلامة'),('accident','حادث'),('emergency','حالة طارئة'),('traffic','حركة المرور'),('transport','النقل'),('economy','الاقتصاد'),('money','المال'),('price','السعر'),('customer','عميل'),('product','منتج'),('service','خدمة'),('quality','جودة'),('education','التعليم'),('knowledge','معرفة'),('skill','مهارة'),('experience','خبرة'),('challenge','تحدٍ'),('opportunity','فرصة'),('goal','هدف'),('progress','تقدم'),('achievement','إنجاز'),('confident','واثق'),('patient','صبور'),('independent','مستقل'),('active','نشيط'),('manage','يدير'),('plan','يخطط'),('solve','يحل'),('recommend','يوصي'),('suggest','يقترح'),('review','يراجع'),('focus','يركز'),('memorize','يحفظ'),('translate','يترجم'),('pronounce','ينطق'),('recognize','يتعرف'),('identify','يحدد'),('select','يختار'),('complete','يكمل'),('achieve','يحقق'),('avoid','يتجنب'),('prevent','يمنع'),('respond','يستجيب'),('consider','يأخذ بعين الاعتبار'),('prefer','يفضل')],
'6': [('communication','التواصل'),('education','التعليم'),('innovation','الابتكار'),('invention','اختراع'),('discovery','اكتشاف'),('scientist','عالم'),('engineer','مهندس'),('society','المجتمع'),('citizen','مواطن'),('government','حكومة'),('resource','مورد'),('electricity','الكهرباء'),('waterfall','شلال'),('agriculture','الزراعة'),('industry','الصناعة'),('tourism','السياحة'),('heritage','التراث'),('architecture','العمارة'),('geography','الجغرافيا'),('continent','قارة'),('distance','مسافة'),('direction','اتجاه'),('location','موقع'),('surface','سطح'),('system','نظام'),('process','عملية'),('method','طريقة'),('evidence','دليل'),('reason','سبب'),('effect','تأثير'),('cause','سبب'),('advantage','ميزة'),('disadvantage','عيب'),('behavior','سلوك'),('relationship','علاقة'),('cooperation','تعاون'),('confidence','ثقة'),('decision','قرار'),('choice','اختيار'),('responsibility','مسؤولية'),('analyze','يحلل'),('evaluate','يقيّم'),('calculate','يحسب'),('estimate','يقدّر'),('investigate','يحقق'),('experiment','يجرب'),('demonstrate','يوضح'),('represent','يمثل'),('organize','ينظم'),('summarize','يلخص'),('participate','يشارك'),('cooperate','يتعاون'),('encourage','يشجع'),('influence','يؤثر'),('require','يتطلب'),('contain','يحتوي'),('depend','يعتمد'),('produce','ينتج'),('consume','يستهلك'),('conserve','يحافظ على')],
'7': [('communication','تواصل'),('identity','هوية'),('diversity','تنوع'),('equality','مساواة'),('freedom','حرية'),('rights','حقوق'),('responsibility','مسؤولية'),('volunteer','متطوع'),('charity','عمل خيري'),('organization','منظمة'),('environmental','بيئي'),('sustainable','مستدام'),('renewable','متجدد'),('ecosystem','نظام بيئي'),('species','نوع'),('extinction','انقراض'),('conservation','حماية الموارد'),('global','عالمي'),('regional','إقليمي'),('urban','حضري'),('rural','ريفي'),('migration','هجرة'),('communication','اتصال'),('media','إعلام'),('advertisement','إعلان'),('audience','جمهور'),('opinion','رأي'),('argument','حجة'),('fact','حقيقة'),('source','مصدر'),('reliable','موثوق'),('accurate','دقيق'),('effective','فعال'),('efficient','كفؤ'),('complex','معقد'),('available','متاح'),('essential','أساسي'),('significant','مهم'),('investigate','يبحث'),('interpret','يفسر'),('compare','يقارن'),('contrast','يبيّن الاختلاف'),('conclude','يستنتج'),('justify','يبرر'),('persuade','يقنع'),('inform','يبلغ'),('mention','يذكر'),('indicate','يشير'),('determine','يحدد'),('establish','ينشئ'),('maintain','يحافظ'),('adapt','يتكيف'),('respond','يستجيب'),('participate','يشارك'),('contribute','يساهم'),('interact','يتفاعل'),('collaborate','يتعاون'),('organize','ينظم'),('prioritize','يرتب الأولويات'),('reflect','يتأمل')],
'8': [('artificial','اصطناعي'),('intelligence','ذكاء'),('algorithm','خوارزمية'),('database','قاعدة بيانات'),('privacy','خصوصية'),('security','أمان'),('password','كلمة مرور'),('platform','منصة'),('application','تطبيق'),('software','برمجيات'),('hardware','عتاد'),('automation','أتمتة'),('virtual','افتراضي'),('creative','إبداعي'),('critical','نقدي'),('strategy','استراتيجية'),('priority','أولوية'),('deadline','موعد نهائي'),('performance','أداء'),('feedback','تغذية راجعة'),('career','مسار مهني'),('profession','مهنة'),('qualification','مؤهل'),('interview','مقابلة'),('employee','موظف'),('employer','صاحب عمل'),('salary','راتب'),('budget','ميزانية'),('expense','مصروف'),('income','دخل'),('investment','استثمار'),('consumer','مستهلك'),('environment','بيئة'),('emission','انبعاث'),('carbon','كربون'),('recycle','يعيد التدوير'),('sustainability','استدامة'),('innovative','مبتكر'),('logical','منطقي'),('flexible','مرن'),('analyze','يحلل'),('optimize','يحسّن'),('generate','يولّد'),('process','يعالج'),('detect','يكتشف'),('classify','يصنف'),('organize','ينظم'),('recommend','يوصي'),('personalize','يخصص'),('monitor','يراقب'),('measure','يقيس'),('calculate','يحسب'),('simulate','يحاكي'),('visualize','يصور'),('verify','يتحقق'),('protect','يحمي'),('update','يحدّث'),('access','يصل إلى'),('connect','يربط'),('share','يشارك')],
'9': [('academic','أكاديمي'),('analysis','تحليل'),('concept','مفهوم'),('context','سياق'),('definition','تعريف'),('principle','مبدأ'),('theory','نظرية'),('hypothesis','فرضية'),('variable','متغير'),('factor','عامل'),('structure','بنية'),('function','وظيفة'),('category','فئة'),('pattern','نمط'),('trend','اتجاه'),('statistics','إحصاءات'),('percentage','نسبة مئوية'),('average','متوسط'),('ratio','نسبة'),('survey','استبيان'),('environmental','بيئي'),('economic','اقتصادي'),('social','اجتماعي'),('cultural','ثقافي'),('political','سياسي'),('scientific','علمي'),('ethical','أخلاقي'),('legal','قانوني'),('professional','مهني'),('technical','تقني'),('relevant','ذو صلة'),('appropriate','مناسب'),('specific','محدد'),('general','عام'),('potential','محتمل'),('primary','أساسي'),('secondary','ثانوي'),('significant','ملحوظ'),('analyze','يحلل'),('assess','يقيّم'),('examine','يفحص'),('identify','يحدد'),('define','يعرّف'),('illustrate','يوضح'),('demonstrate','يبرهن'),('compare','يقارن'),('contrast','يقارن الاختلاف'),('evaluate','يقيّم'),('interpret','يفسر'),('summarize','يلخص'),('cite','يستشهد'),('reference','يرجع إلى'),('organize','ينظم'),('present','يعرض'),('discuss','يناقش'),('argue','يجادل'),('support','يدعم'),('challenge','يتحدى'),('question','يتساءل'),('conclude','يستنتج')],
'10': [('research','بحث'),('methodology','منهجية'),('evidence','دليل'),('validity','صلاحية'),('reliability','موثوقية'),('bias','تحيز'),('sample','عينة'),('population','مجتمع إحصائي'),('correlation','ارتباط'),('causation','سببية'),('innovation','ابتكار'),('entrepreneur','رائد أعمال'),('business','أعمال'),('market','سوق'),('competition','منافسة'),('strategy','استراتيجية'),('management','إدارة'),('leadership','قيادة'),('productivity','إنتاجية'),('efficiency','كفاءة'),('technology','تقنية'),('engineering','هندسة'),('medicine','طب'),('biology','أحياء'),('chemistry','كيمياء'),('physics','فيزياء'),('mathematics','رياضيات'),('literature','أدب'),('philosophy','فلسفة'),('psychology','علم النفس'),('complex','معقد'),('abstract','مجرد'),('objective','موضوعي'),('subjective','ذاتي'),('consistent','متسق'),('accurate','دقيق'),('precise','دقيق جدًا'),('efficient','كفؤ'),('sustainable','مستدام'),('innovative','مبتكر'),('formulate','يصوغ'),('investigate','يبحث'),('measure','يقيس'),('calculate','يحسب'),('interpret','يفسر'),('evaluate','يقيم'),('synthesize','يركب الأفكار'),('justify','يبرر'),('predict','يتنبأ'),('estimate','يقدّر'),('propose','يقترح'),('implement','ينفذ'),('monitor','يراقب'),('modify','يعدل'),('validate','يتحقق من الصحة'),('document','يوثق'),('communicate','يتواصل'),('collaborate','يتعاون'),('negotiate','يتفاوض'),('resolve','يحل')],
'11': [('perspective','منظور'),('assumption','افتراض'),('implication','دلالة'),('consequence','نتيجة'),('criterion','معيار'),('framework','إطار'),('approach','نهج'),('interpretation','تفسير'),('evaluation','تقييم'),('assessment','تقدير'),('innovation','ابتكار'),('transformation','تحول'),('globalization','عولمة'),('economy','اقتصاد'),('inflation','تضخم'),('employment','توظيف'),('productivity','إنتاجية'),('investment','استثمار'),('finance','تمويل'),('entrepreneurship','ريادة الأعمال'),('democracy','ديمقراطية'),('citizenship','مواطنة'),('legislation','تشريع'),('policy','سياسة'),('institution','مؤسسة'),('sustainability','استدامة'),('biodiversity','تنوع حيوي'),('renewable','متجدد'),('emission','انبعاث'),('climate','مناخ'),('controversial','مثير للجدل'),('comprehensive','شامل'),('fundamental','جوهري'),('alternative','بديل'),('contemporary','معاصر'),('emerging','ناشئ'),('strategic','استراتيجي'),('ethical','أخلاقي'),('analyze','يحلل'),('critique','ينقد'),('justify','يبرر'),('synthesize','يركب'),('infer','يستدل'),('formulate','يصوغ'),('articulate','يعبر بوضوح'),('investigate','يبحث'),('evaluate','يقيم'),('prioritize','يرتب الأولويات'),('anticipate','يتوقع'),('adapt','يتكيف'),('implement','ينفذ'),('facilitate','يسهّل'),('coordinate','ينسق'),('allocate','يخصص'),('regulate','ينظم'),('influence','يؤثر'),('negotiate','يتفاوض'),('advocate','يدافع'),('participate','يشارك'),('contribute','يسهم')],
'12': [('autonomy','استقلالية'),('accountability','مساءلة'),('integrity','نزاهة'),('credibility','مصداقية'),('competence','كفاءة'),('resilience','مرونة'),('adaptability','قدرة على التكيف'),('leadership','قيادة'),('entrepreneurship','ريادة الأعمال'),('innovation','ابتكار'),('sustainability','استدامة'),('globalization','عولمة'),('digitalization','رقمنة'),('automation','أتمتة'),('cybersecurity','أمن سيبراني'),('economics','اقتصاد'),('finance','تمويل'),('investment','استثمار'),('governance','حوكمة'),('legislation','تشريع'),('ethics','أخلاقيات'),('research','بحث'),('methodology','منهجية'),('literature','أدبيات'),('hypothesis','فرضية'),('analysis','تحليل'),('evaluation','تقييم'),('interpretation','تفسير'),('conclusion','استنتاج'),('recommendation','توصية'),('comprehensive','شامل'),('sophisticated','متطور'),('innovative','مبتكر'),('sustainable','مستدام'),('strategic','استراتيجي'),('significant','مهم'),('relevant','ذو صلة'),('credible','موثوق'),('formulate','يصوغ'),('synthesize','يركب الأفكار'),('evaluate','يقيم'),('validate','يتحقق'),('substantiate','يدعم بالدليل'),('interpret','يفسر'),('differentiate','يميز'),('integrate','يدمج'),('implement','ينفذ'),('optimize','يحسن'),('coordinate','ينسق'),('facilitate','يسهل'),('negotiate','يتفاوض'),('advocate','يدافع'),('anticipate','يتوقع'),('mitigate','يخفف'),('prioritize','يرتب الأولويات'),('allocate','يخصص'),('monitor','يراقب'),('document','يوثق'),('communicate','يتواصل'),('collaborate','يتعاون')]
}


def make_examples(word, meaning, grade):
    en = f'We used the word "{word}" in a clear English sentence during class.'
    ar = f'استخدمنا كلمة «{meaning}» في جملة إنجليزية واضحة أثناء الدرس.'
    return en, ar


data = json.loads(PATH.read_text(encoding='utf-8'))
data['version'] = 4
data['app'] = 'قاموسي AI'
words = data.get('words', [])
for w in words:
    w['source'] = 'Global Arabic student vocabulary'
    if not str(w.get('example_en','')).strip():
        en, ar = make_examples(str(w.get('word_en','')).strip(), str(w.get('meaning_ar','')).strip(), str(w.get('grade','')))
        w['example_en'] = en
        w['example_ar'] = ar

existing = {(str(w.get('grade','')), str(w.get('word_en','')).strip().lower()) for w in words}
next_id = max([int(w.get('id',0) or 0) for w in words] + [0]) + 1
added = {}
for grade, candidates in grades.items():
    count = 0
    for word, meaning in candidates:
        key = (grade, word.lower())
        if key in existing:
            continue
        en, ar = make_examples(word, meaning, grade)
        words.append({
            'id': next_id,
            'grade': grade,
            'word_en': word,
            'meaning_ar': meaning,
            'example_en': en,
            'example_ar': ar,
            'semester': '',
            'unit': 'Global AI Core',
            'lesson': 'Smart Vocabulary',
            'source': 'Qamoosi AI global core vocabulary'
        })
        next_id += 1
        existing.add(key)
        count += 1
        if count >= 50:
            break
    if count < 50:
        raise SystemExit(f'Grade {grade}: only {count} new words; need at least 50')
    added[grade] = count

data['words'] = words
PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
print('Added:', added)
print('Total words:', len(words))
