from pathlib import Path
import re

p = Path('lib/main.dart')
text = p.read_text(encoding='utf-8')

text = re.sub(r"const appVersion = '[^']+';", "const appVersion = '2.2.0';", text, count=1)

# Accept every sentence field used by JSON/Excel/PWA exports.
text = text.replace("exampleEn: '${j['example_en'] ?? j['example'] ?? ''}'.trim(),", "exampleEn: '${j['example_en'] ?? j['sentence_en'] ?? j['example'] ?? j['sentence'] ?? ''}'.trim(),")
text = text.replace("exampleAr: '${j['example_ar'] ?? j['translation'] ?? ''}'.trim(),", "exampleAr: '${j['example_ar'] ?? j['sentence_ar'] ?? j['translation'] ?? j['sentence_translation'] ?? ''}'.trim(),")

text = text.replace("['example_en', 'sentence_en', 'example', 'الجملة_الإنجليزية', 'مثال_إنجليزي']", "['example_en', 'sentence_en', 'example', 'sentence', 'الجملة_الإنجليزية', 'الجملة_الانجليزية', 'جملة_مثال', 'مثال_من_الكتاب', 'مثال_إنجليزي']")
text = text.replace("['example_ar', 'sentence_ar', 'translation', 'ترجمة_الجملة', 'مثال_عربي']", "['example_ar', 'sentence_ar', 'translation', 'sentence_translation', 'ترجمة_الجملة', 'ترجمة_المثال', 'ترجمة_المثال_إلى_العربية', 'مثال_عربي']")

# Make sentence UI explicit: sentence first, pronunciation button, then Arabic translation.
old = """if (showExample) Container(\n                            margin: const EdgeInsets.only(top: 20),\n                            padding: const EdgeInsets.all(16),\n                            decoration: BoxDecoration(color: Theme.of(context).colorScheme.secondaryContainer, borderRadius: BorderRadius.circular(18)),\n                            child: Column(children: [\n                              if (word.exampleEn.isNotEmpty) Row(children: [\n                                Expanded(child: Text(word.exampleEn, textDirection: TextDirection.ltr, textAlign: TextAlign.center, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700))),\n                                IconButton(onPressed: () => pronounce(context, word.exampleEn), icon: const Icon(Icons.volume_up_rounded)),\n                              ]),\n                              if (word.exampleAr.isNotEmpty) Text(word.exampleAr, textAlign: TextAlign.center),\n                            ]),\n                          ),"""
new = """if (showExample) Container(\n                            margin: const EdgeInsets.only(top: 20),\n                            padding: const EdgeInsets.all(16),\n                            decoration: BoxDecoration(color: Theme.of(context).colorScheme.secondaryContainer, borderRadius: BorderRadius.circular(18)),\n                            child: Column(children: [\n                              if (word.exampleEn.isNotEmpty) ...[\n                                const Text('الجملة الإنجليزية', style: TextStyle(fontWeight: FontWeight.w800)),\n                                const SizedBox(height: 8),\n                                Text(word.exampleEn, textDirection: TextDirection.ltr, textAlign: TextAlign.center, style: const TextStyle(fontSize: 19, fontWeight: FontWeight.w700)),\n                                const SizedBox(height: 8),\n                                FilledButton.tonalIcon(onPressed: () => pronounce(context, word.exampleEn), icon: const Icon(Icons.volume_up_rounded), label: const Text('لفظ الجملة')),\n                              ],\n                              if (word.exampleAr.isNotEmpty) ...[\n                                const SizedBox(height: 14),\n                                const Divider(),\n                                const SizedBox(height: 8),\n                                const Text('ترجمة الجملة', style: TextStyle(fontWeight: FontWeight.w800)),\n                                const SizedBox(height: 6),\n                                Text(word.exampleAr, textAlign: TextAlign.center, style: const TextStyle(fontSize: 17)),\n                              ],\n                            ]),\n                          ),"""
text = text.replace(old, new)

old2 = """if (showExample) Container(width: double.infinity, margin: const EdgeInsets.only(top: 20), padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: Theme.of(context).colorScheme.secondaryContainer, borderRadius: BorderRadius.circular(20)), child: Column(children: [\n                    if (word.exampleEn.isNotEmpty) Row(children: [Expanded(child: Text(word.exampleEn, textDirection: TextDirection.ltr, textAlign: TextAlign.center, style: const TextStyle(fontSize: 19, fontWeight: FontWeight.w700))), IconButton.filledTonal(onPressed: () => pronounce(word.exampleEn), icon: const Icon(Icons.volume_up_rounded))]),\n                    if (word.exampleAr.isNotEmpty) Padding(padding: const EdgeInsets.only(top: 8), child: Text(word.exampleAr, textAlign: TextAlign.center)),\n                  ])),"""
new2 = """if (showExample) Container(width: double.infinity, margin: const EdgeInsets.only(top: 20), padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: Theme.of(context).colorScheme.secondaryContainer, borderRadius: BorderRadius.circular(20)), child: Column(children: [\n                    if (word.exampleEn.isNotEmpty) ...[\n                      const Text('الجملة الإنجليزية', style: TextStyle(fontWeight: FontWeight.w800)),\n                      const SizedBox(height: 8),\n                      Text(word.exampleEn, textDirection: TextDirection.ltr, textAlign: TextAlign.center, style: const TextStyle(fontSize: 19, fontWeight: FontWeight.w700)),\n                      const SizedBox(height: 10),\n                      SizedBox(width: double.infinity, child: FilledButton.tonalIcon(onPressed: () => pronounce(word.exampleEn), icon: const Icon(Icons.volume_up_rounded), label: const Text('لفظ الجملة'))),\n                    ],\n                    if (word.exampleAr.isNotEmpty) ...[\n                      const SizedBox(height: 14),\n                      const Divider(),\n                      const Text('ترجمة الجملة', style: TextStyle(fontWeight: FontWeight.w800)),\n                      const SizedBox(height: 6),\n                      Text(word.exampleAr, textAlign: TextAlign.center, style: const TextStyle(fontSize: 17)),\n                    ],\n                  ])),"""
text = text.replace(old2, new2)

p.write_text(text, encoding='utf-8')
