from pathlib import Path
import re

p = Path('lib/main.dart')
s = p.read_text(encoding='utf-8')

s = s.replace("const appVersion = '3.4.7';", "const appVersion = '3.4.8';")

old_pdf = '''      final document = await PdfDocument.openFile(file.path!);\n      final pages = <String>[];\n      try {\n        for (final page in document.pages) {\n          final pageText = await page.loadText();\n          pages.add(pageText?.fullText ?? '');\n        }\n      } finally {\n        await document.dispose();\n      }\n      final map = <String, BookCandidate>{};\n      String currentUnit = '';\n      String currentLesson = '';\n      for (var pi = 0; pi < pages.length; pi++) {\n        final text = pages[pi];\n        final unitMatch = RegExp(r'\\bUnit\\s+([0-9]+|[A-Za-z]+)', caseSensitive: false).firstMatch(text);\n        final lessonMatch = RegExp(r'\\bLesson\\s+([0-9]+|[A-Za-z]+)', caseSensitive: false).firstMatch(text);\n        if (unitMatch != null) { final v = (unitMatch.group(1) ?? '').trim(); if (v.isNotEmpty && v.toLowerCase() != 'unit') currentUnit = 'Unit $v'; }\n        if (lessonMatch != null) { final v = (lessonMatch.group(1) ?? '').trim(); if (v.isNotEmpty && v.toLowerCase() != 'lesson') currentLesson = 'Lesson $v'; }\n\n        final tokens = RegExp(r\"[A-Za-z][A-Za-z'-]*\").allMatches(text).toList();\n        for (var ti = 0; ti < tokens.length; ti++) {\n          final raw = tokens[ti].group(0)!;\n          final prefixStart = tokens[ti].start > 2 ? tokens[ti].start - 2 : 0;\n          final prefix = text.substring(prefixStart, tokens[ti].start);\n          final startsSentence = ti == 0 || RegExp(r'[.!?]\\s*$').hasMatch(prefix);\n          if (!_validWord(raw, midSentenceTitleCase: !startsSentence)) continue;\n          final key = raw.toLowerCase();\n          final existing = _existingWord(raw);\n          final found = map[key];\n          if (found != null) {\n            found.frequency++;\n            if (found.exampleEn.isEmpty) found.exampleEn = _sentenceFor(text, raw);\n          } else {\n            map[key] = BookCandidate(\n              word: raw.toLowerCase(),\n              meaning: existing?.ar ?? '',\n              exampleEn: _sentenceFor(text, raw),\n              exampleAr: existing?.exampleAr ?? '',\n              unit: currentUnit,\n              lesson: currentLesson,\n              page: '${pi + 1}',\n            );\n          }\n        }\n      }\n      final list = map.values.toList(growable: true);\n      setState(() { candidates = list; pagesRead = pages.length; });'''

new_pdf = '''      final document = await PdfDocument.openFile(file.path!);\n      final map = <String, BookCandidate>{};\n      String currentUnit = '';\n      String currentLesson = '';\n      var completedPages = 0;\n      try {\n        for (var pi = 0; pi < document.pages.length; pi++) {\n          final pageText = await document.pages[pi].loadText();\n          final text = pageText?.fullText ?? '';\n          final unitMatch = RegExp(r'\\bUnit\\s+([0-9]+|[A-Za-z]+)', caseSensitive: false).firstMatch(text);\n          final lessonMatch = RegExp(r'\\bLesson\\s+([0-9]+|[A-Za-z]+)', caseSensitive: false).firstMatch(text);\n          if (unitMatch != null) { final v = (unitMatch.group(1) ?? '').trim(); if (v.isNotEmpty && v.toLowerCase() != 'unit') currentUnit = 'Unit $v'; }\n          if (lessonMatch != null) { final v = (lessonMatch.group(1) ?? '').trim(); if (v.isNotEmpty && v.toLowerCase() != 'lesson') currentLesson = 'Lesson $v'; }\n\n          final tokens = RegExp(r\"[A-Za-z][A-Za-z'-]*\").allMatches(text).toList();\n          for (var ti = 0; ti < tokens.length; ti++) {\n            final raw = tokens[ti].group(0)!;\n            final prefixStart = tokens[ti].start > 2 ? tokens[ti].start - 2 : 0;\n            final prefix = text.substring(prefixStart, tokens[ti].start);\n            final startsSentence = ti == 0 || RegExp(r'[.!?]\\s*$').hasMatch(prefix);\n            if (!_validWord(raw, midSentenceTitleCase: !startsSentence)) continue;\n            final key = raw.toLowerCase();\n            final existing = _existingWord(raw);\n            final found = map[key];\n            if (found != null) {\n              found.frequency++;\n              if (found.exampleEn.isEmpty) found.exampleEn = _sentenceFor(text, raw);\n            } else {\n              map[key] = BookCandidate(\n                word: raw.toLowerCase(),\n                meaning: existing?.ar ?? '',\n                exampleEn: _sentenceFor(text, raw),\n                exampleAr: existing?.exampleAr ?? '',\n                unit: currentUnit,\n                lesson: currentLesson,\n                page: '${pi + 1}',\n              );\n            }\n          }\n          completedPages = pi + 1;\n          if (mounted && (completedPages == 1 || completedPages % 4 == 0 || completedPages == document.pages.length)) {\n            setState(() {\n              pagesRead = completedPages;\n              candidates = map.values.toList(growable: true);\n            });\n          }\n        }\n      } finally {\n        await document.dispose();\n      }\n      final list = map.values.toList(growable: true);\n      if (mounted) setState(() { candidates = list; pagesRead = completedPages; });'''

if old_pdf not in s:
    raise SystemExit('PDF block not found')
s = s.replace(old_pdf, new_pdf)

# Quick Cards: official label/counter and useful content visible immediately.
s = s.replace('  bool showMeaning = false;\n  bool showExample = false;', '  bool showMeaning = true;\n  bool showExample = true;')
s = s.replace('      showMeaning = false;\n      showExample = false;', '      showMeaning = true;\n      showExample = true;')
s = s.replace("appBar: AppBar(title: Text('بطاقة الكلمة ${index + 1} / ${widget.words.length}')),", "appBar: AppBar(title: Column(mainAxisSize: MainAxisSize.min, children: [const Text('بطاقات سريعة'), Text('${index + 1} من ${widget.words.length}', style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700))])),")

p.write_text(s, encoding='utf-8')

pub = Path('pubspec.yaml')
ps = pub.read_text(encoding='utf-8')
ps = re.sub(r'^version:\s*3\.4\.7\+36$', 'version: 3.4.8+37', ps, flags=re.M)
pub.write_text(ps, encoding='utf-8')
print('Easy English AI v3.4.8 PDF and Quick Cards polish applied')
